[project]
name = "bse-dsdm-moises"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Moises", email = "mocame96@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
]

[project.scripts]
bse-dsdm-moises = "bse_dsdm_moises:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
